# Generated by Django 5.1.1 on 2024-10-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="Mobile_Number",
            field=models.CharField(unique=True),
        ),
    ]
