# Generated by Django 5.1.1 on 2024-10-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts_app", "0002_alter_user_mobile_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Full_Name", models.CharField(max_length=50, unique=True)),
                ("Mobile_Number", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="Mobile_Number",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
