# Generated by Django 5.1.1 on 2024-10-12 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts_app", "0006_user_contacts"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User_Contacts",
        ),
    ]
