# Generated by Django 5.1.1 on 2024-10-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts_app", "0007_delete_user_contacts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Full_Name", models.CharField(max_length=50)),
                ("Mobile_Number", models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
