# Generated by Django 5.1.1 on 2024-10-12 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts_app", "0008_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contacts_app.contact",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="contacts_app.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "contact")},
            },
        ),
    ]
