# Generated by Django 5.1.1 on 2024-10-12 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts_app", "0009_user_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="Mobile_Number",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="user_contacts",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="contacts_app.contact",
            ),
        ),
        migrations.AlterField(
            model_name="user_contacts",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_contacts",
                to="contacts_app.user",
            ),
        ),
    ]
