# Generated by Django 5.1.1 on 2024-10-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_Name", models.CharField(max_length=50)),
                ("Last_Name", models.CharField(max_length=50)),
                ("Email", models.CharField(max_length=50, unique=True)),
                ("Mobile_Number", models.CharField(max_length=10, unique=True)),
                ("Password", models.CharField(max_length=50)),
            ],
        ),
    ]
